### ISSUE TITLE
Deadlock in GrpcClient

### ISSUE THREAD

**Issue by arnaudbos** [IBM/etcd-java#16]
We are encountering a deadlock issue in production inside the `GrpcClient#waitFor` method when called from `AbstractFluentRequest#sync` and there is a deadline exceeded.

We managed to reproduce the issue with very short timeouts in a unit test in the following [test project](https://github.com/arnaudbos/ibm-etcd-java-deadlock-repro).

We suspect this issue was introduced with the addition of the `ThreadlessExecutor` and error management done in fallback logic which may create a Futures.immediateFailedFuture(t) that may not call the given executor.
This manifests as a deadlock on the `waitAndDrain` method.

We have not been able to untangle the inner details of the issue to provide a patch, let us know if you need more investigation on our end.

Best regards

**Comment by njhill** [comment]
Thanks for reporting this @arnaudbos. I was unable to reproduce immediately using your example (appeared to work fine for me), however from your description and looking at the code I can see there's almost certainly an issue, I will fix it asap.

I wonder if you could provide a bit more detail just in case: your OS and JVM version, and the stacktrace of the stuck thread if possible?

**Comment by arnaudbos** [comment]
The behavior is inconsistent across retries on our end too, we reproduce it almost every time in our staging environment, but the repro test passes 4 times out of 5 on average before junit reports a timeout failure.

Our dev machines are pretty much all the same: Ubuntu 16.04.1:

```shell
λ uname -a                                                                                                                        
Linux DEV 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Our production containers are custom Centos 7.4 images.

We run the java-1.8.0-openjdk both in dev and production: 1.8.0_181.

Following are the relevant parts of the threads report as outputted by dropwizard.

You can see we have three threads blocked by a fourth (notifier-io-1), waiting to acquire the intrinsic lock on this `CachedSchemaRegistryClient` object.

(FYI this is a homemade "Avro Schema Registry" implementation for Kafka, so this happens on the first `send` of a message with an uncached Avro schema that has to be "registered" to Etcd, once registered the schema's registration ID is cached locally, but the inner details and logic are irrelevant I think.)

This is a client's project so we had to omit the package names for privacy reasons.

```
"notifier-io-0" id=47 state=BLOCKED
    - waiting to lock <0x182af627> (a com.[...].registry.CachedSchemaRegistryClient)
     owned by notifier-io-1 id=48
    at com.[...].registry.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:149)
    at com.[...].serializers.KafkaAvroSerializer.serializeImpl(KafkaAvroSerializer.java:60)
    at com.[...].serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:42)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55)
    at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:768)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:745)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier.lambda$2(TransformingKafkaNotifier.java:88)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier$$Lambda$357/449852554.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@5a185d51

"notifier-io-1" id=48 state=WAITING
    - waiting on <0x4968b048> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x4968b048> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
    at com.ibm.etcd.client.GrpcClient$ThreadlessExecutor.waitAndDrain(GrpcClient.java:706)
    at com.ibm.etcd.client.GrpcClient.waitFor(GrpcClient.java:621)
    at com.ibm.etcd.client.kv.EtcdKvClient$AbstractFluentRequest.sync(EtcdKvClient.java:216)
    at com.ibm.etcd.client.kv.EtcdKvClient$EtcdTxnRequest$EtcdTxnOps.sync(EtcdKvClient.java:556)
    at com.ibm.etcd.client.kv.EtcdKvClient$EtcdTxnRequest$EtcdTxnOps.sync(EtcdKvClient.java:481)
    at com.[...].registry.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:80)
    at com.[...].registry.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:167)
    at com.[...].serializers.KafkaAvroSerializer.serializeImpl(KafkaAvroSerializer.java:60)
    at com.[...].serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:42)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55)
    at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:768)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:745)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier.lambda$2(TransformingKafkaNotifier.java:88)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier$$Lambda$357/449852554.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@5212afe5

"notifier-io-2" id=49 state=BLOCKED
    - waiting to lock <0x182af627> (a com.[...].registry.CachedSchemaRegistryClient)
     owned by notifier-io-1 id=48
    at com.[...].registry.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:149)
    at com.[...].serializers.KafkaAvroSerializer.serializeImpl(KafkaAvroSerializer.java:60)
    at com.[...].serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:42)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55)
    at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:768)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:745)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier.lambda$2(TransformingKafkaNotifier.java:88)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier$$Lambda$357/449852554.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@7a898721

"notifier-io-3" id=50 state=BLOCKED
    - waiting to lock <0x182af627> (a com.[...].registry.CachedSchemaRegistryClient)
     owned by notifier-io-1 id=48
    at com.[...].registry.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:149)
    at com.[...].serializers.KafkaAvroSerializer.serializeImpl(KafkaAvroSerializer.java:60)
    at com.[...].serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:42)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65)
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55)
    at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:768)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:745)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier.lambda$2(TransformingKafkaNotifier.java:88)
    at com.[...].dm.harvester.core.transform.TransformingKafkaNotifier$$Lambda$357/449852554.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

    Locked synchronizers: count = 1
      - java.util.concurrent.ThreadPoolExecutor$Worker@3cfb53d8
```

The following is the stacktrace of the stuck test:

```
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds

	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.ibm.etcd.client.GrpcClient$ThreadlessExecutor.waitAndDrain(GrpcClient.java:706)
	at com.ibm.etcd.client.GrpcClient.waitFor(GrpcClient.java:621)
	at com.ibm.etcd.client.kv.EtcdKvClient$AbstractFluentRequest.sync(EtcdKvClient.java:216)
	at io.monkeypatch.etcd.debug.EtcdDeadlockIntegrationTest.lambda$testEtcdClient$0(EtcdDeadlockIntegrationTest.java:81)
	at io.monkeypatch.etcd.debug.EtcdDeadlockIntegrationTest$$Lambda$53/3067486.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at io.monkeypatch.etcd.debug.EtcdDeadlockIntegrationTest.testEtcdClient(EtcdDeadlockIntegrationTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks for your support, let us know if we can help.

**Comment by njhill** [comment]
@arnaudbos thanks for the additional detail. I was able to reproduce in the end by just setting a higher count! The bug is fixed in #17, I will release a new version at some point after this is merged. I was hoping to wait for grpc-java 1.16 to be released first but if that's not imminent I may do a release anyhow. Thanks again

**Comment by arnaudbos** [comment]
Great, thanks again for the hard work and sorry we couldn't provide a patch ourselves.  

The fix looks good to me, we've increased and parameterized our timeouts in order to avoid the issue and look forward to the next release!

Not sure whether I should close the issue now or not, I'll let you handle this :+1:
