### ISSUE TITLE
RangeCache delete method hangs indefinitely?

### ISSUE THREAD

**Issue by sherman** [IBM/etcd-java#48]
Hi, Nick!
Thank you for a good job.
Seems, I've encountered a problem with RangeCache.
Sometimes, I need to delete some nodes from a range cache explicitly. So I call the remove method for that. Unfortunately, from time to time, the method hangs.

Here's the code.
```
@Override
protected void doStop() {
    synchronized (nodes) {
        try {
            nodes.close();
            if (localNode != null) {
                removeNode(localNode);
            }
        } catch (Exception e) {
            log.error("Can't close range cache", e);
        }
    }
 }
```

nodes - RangeCache instance

```
public void removeNode(Node node) {
    boolean deleted = nodes.delete(bs(configuration.getNodePrefixPath().concat(node.getServerId())));
    log.debug("Node is removed: {}", deleted);
}
```

Here's the stack trace.

```
"Test worker" #22 prio=5 os_prio=0 cpu=1199.21ms elapsed=147517.01s tid=0x00007fbe64bc3000 nid=0xd3193 waiting on condition  [0x00007fbe3a1b4000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
        - parking to wait for  <0x00000000e157bc10> (a com.ibm.etcd.client.GrpcClient$ThreadlessExecutor)
        at java.util.concurrent.locks.LockSupport.park(java.base@14.0.2/LockSupport.java:211)
        at com.ibm.etcd.client.GrpcClient$ThreadlessExecutor.waitAndDrain(GrpcClient.java:879)
        at com.ibm.etcd.client.GrpcClient.waitFor(GrpcClient.java:768)
        at com.ibm.etcd.client.GrpcClient.waitForCall(GrpcClient.java:729)
        at com.ibm.etcd.client.FluentRequest$AbstractFluentRequest.sync(FluentRequest.java:103)
        at com.ibm.etcd.client.utils.RangeCache.delete(RangeCache.java:844)
        at ru.ozon.platform.cluster.service.EtcdNodeRepository.removeNode(EtcdNodeRepository.java:61)
        at ru.ozon.platform.cluster.service.EtcdNodeRepository.doStop(EtcdNodeRepository.java:122)
        - locked <0x00000000e157bd18> (a com.ibm.etcd.client.utils.RangeCache)
        at com.google.common.util.concurrent.AbstractService.stopAsync(AbstractService.java:281)
        at com.google.common.util.concurrent.ServiceManager.stopAsync(ServiceManager.java:336)
        at ru.ozon.platform.common.ClusterMembershipApiIT.tearDownHost(ClusterMembershipApiIT.java:58)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@14.0.2/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@14.0.2/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@14.0.2/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@14.0.2/Method.java:564)

```

I suppose there's a bug in my code because I call close() before remove()?

But, is it normal behavior that code continues work and method just hang?

An additional remove method with a deadline for the whole GRPC request might help? 
Or I'd expect an exception here about this abnormal situation.

What do you think?

**Comment by sherman** [comment]
The bug is reproduced even If call remove() BEFORE close(). As I can see, there's no relation between the two methods and the bug in remove() method itself.

**Comment by sherman** [comment]
Also, I think the root cause might be in the fact that the ETCD client is already closed when the method is called. I'd expected the exception in this situation because you can't do the call to a closed client.

**Comment by sherman** [comment]
Confirmed. When I fixed the problem with closing a client, the problems gone.

**Comment by njhill** [comment]
Hi @sherman, thanks for the report. I was unable to reproduce this - the call to `delete()` always throws an exception if the client has already been closed. Could you share the versions of etcd-java and grpc that you are using? Also I noticed that you're using java 14. Any chance you could try this with an earlier version e.g. 11?

If you are using latest versions of the libs, any chance you could provide a minimal reproducer?

**Comment by sherman** [comment]
Hi, @njhill.
Seems, was a problem in my application. Unfortunately, I couldn't reproduce it as a standalone example. So, I believe, this issue should be closed.
