### ISSUE TITLE
Could not initialize class com.ibm.etcd.api.V3Lock

### ISSUE THREAD

**Issue by taoyangzhou** [IBM/etcd-java#64]
use lock has an error:
java.lang.NoClassDefFoundError: Could not initialize class com.ibm.etcd.api.V3Lock
	at com.ibm.etcd.api.LockResponse.internalGetFieldAccessorTable(LockResponse.java:97)
	at com.google.protobuf.GeneratedMessageV3.getAllFieldsMutable(GeneratedMessageV3.java:124)
	at com.google.protobuf.GeneratedMessageV3.getAllFields(GeneratedMessageV3.java:200)
	at com.alibaba.fastjson.serializer.ASMSerializer_8_LockResponse.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:312)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:769)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:707)

**Comment by njhill** [comment]
@taoyangzhou you'll have to provide some more details. There should be another exception or cause showing _why_ the class couldn't be initialized.

**Comment by njhill** [comment]
Closing due to lack of response.
